name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project with Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          KEYCLOAK_TRANSACTIONAL_EMAIL: ${{ secrets.GITHUB_TOKEN }}
      - name: Add JaCoCo Coverage to Action Summary
        uses: jjmrocha/jacoco-summary@v1.1.1
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml
          retention-days: 1
